flaskApp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired,Length



class PostForm(FlaskForm):
    title = StringField("title", validators=[
        DataRequired(),
        Length(min=3)
    ])
    content = TextAreaField("content", validators=[
        DataRequired()
    ])


    submit = SubmitField("Create Post")

flaskApp/main/routes.py
from flask import Blueprint,render_template,request 
from flask_login import login_required
from flaskApp.models import Post
main = Blueprint("main",__name__)


@main.route("/")
@main.route("/home")
@login_required
def home():
    page = request.args.get("page",1,type=int)
    posts = Post.query.paginate(page=page,per_page=5)
    return render_template("home.html", title="Home", posts=posts)


@main.route("/about")
@login_required
def about():
    return render_template("about.html", title="About")

flaskApp/posts/routes.py
from flask import Blueprint,render_template,redirect,url_for,request,flash,abort
from flask_login import login_required,current_user
from flaskApp import db,mail,bcrypt
from flaskApp.models import Post 
from flaskApp.posts.forms import PostForm
posts = Blueprint("posts",__name__)


@posts.route("/post/<int:post_id>")
@login_required
def get_post(post_id):
    pass







@posts.route("/post",methods=["GET","POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("You successfully created an Post","success")
        return redirect(url_for("main.home"))
    return render_template("post_form.html", title="Create Post", legend="Create Post",form=form)


@posts.route("/post/<int:post_id>/update",methods=["GET","POST"])
@login_required
def update_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if form.validate_on_submit():
        post.title = form.title.data   
        post.content = form.content.data
        db.session.commit()
        flash("Your Post has been updated!","success")
        return redirect(url_for("main.home"))
    elif request.method ==  "GET":
        form.title.data = post.title   
        form.content.data = post.content
    return render_template("post_form.html", title="Update Post", legend="Update Post",form=form)


@posts.route("/delete/<int:post_id>")
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your Post has been deleted!","success")
    return redirect(url_for("main.home"))

flaskApp/users/routes.py
from flask import Blueprint,render_template,flash,redirect,url_for,request
from flask_login import current_user,login_user,logout_user,login_required
from flaskApp import db,bcrypt
from flaskApp.users.forms import RegisterForm,LoginForm,Request_reset_form,Reset_password_form,UpdateUserForm
from flaskApp.models import User
from flaskApp.users.utils import save_file,send_reset_email
users = Blueprint("users",__name__)



@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("You are now Registered!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Wrong Credentials","danger")
    return render_template("login.html",title="Login",form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/account",methods=["GET","POST"])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_file(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data   
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated","success")
        return redirect(url_for("main.home")) 
        
    elif request.method == "GET":
            form.username.data = current_user.username 
            form.email.data = current_user.email 
    image_file = url_for("static",filename="profile_pics/" + current_user.image_file)
    return render_template("account.html",title="Account",form=form,image_file=image_file)

@users.route("/user/<string:username>")
@login_required
def get_user(username):
    pass



@users.route("/reset_password",methods=["GET","POST"])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = Request_reset_form()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sended to this email address","info")
        return redirect(url_for('users.login'))
    return render_template("request_password.html",form=form,title="Reset Password")


@users.route("/reset_password/<token>",methods=["GET","POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("Invalid/Expired token","danger")
        return redirect(url_for('users.reset_password_request'))
    form = Reset_password_form()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been changed!","success")
        return redirect(url_for('users.login'))
    return render_template("reset_token.html",title="Reset Password",form=form)

flaskApp/templates/about.html
{% extends "base.html" %}


{% block content %}
<div>
    <h1>About</h1>
</div>
{% endblock %}

flaskApp/templates/account.html
{% extends "base.html" %}


{% block content %}
<div class="container">
    <h3 class="text-center mb-5">Account details</h3>
    <div class="card shadow-lg bg-white rounded mb-5">
        <div class="card-body">
            <form method="POST" action="" enctype="multipart/form-data">
           
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control") }}
                {% endif %}
                
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group mt-3">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}

            </div>
            <div class="form-group mt-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div> 
        </form>
        </div>
    </div>
</div>
{% endblock %}

flaskApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  
    <link rel="stylesheet" href="{{ url_for('static',filename="main.css") }}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
      {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask App</title>
    {% endif %}
</head>
<body>
<div  style="background: url('../static/background-image/background.jpg') no-repeat center center fixed;
background-size:cover;">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand text-white" href="{{ url_for('main.home') }}">Home</a>
           <ul class="navbar-nav">
             <li class="nav-item">
                <a class="nav-link text-white" href="{{ url_for('main.about') }}">About</a>
            </li>      
           {% if current_user.is_authenticated %}
           <li class="nav-item">
                <a class="nav-link text-white" href="{{ url_for('posts.create_post') }}">create Post</a>
            </li>
     
            <li class="nav-item">
                <a class="nav-link text-white" href="{{ url_for('users.logout') }}">Logout</a>
            </li>
           {% else %}
                  <li class="nav-item" >
                <a class="nav-link ml-auto text-white" href="{{ url_for('users.register') }}">Register</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link ml-auto text-white" href="{{ url_for('users.login') }}">Login</a>
            </li>
           {% endif %}
                
       
        </ul>
        
    </nav>
    <!-- Content -->
    <div class="container">
    {% with messages = get_flashed_messages(with_categories=true)  %}
        {% if messages %}
            {% for category,message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>
    <div  style="height: 100vh; width:100vw">
    {% block content %}
    {% endblock %}
    </div>
    </div>
</body>
</html>

flaskApp/templates/home.html
{% extends "base.html" %}


{% block content %}
<div class="container">
    <h1 class="text-center mb-5">Home</h1>
    <hr/>
    <div class="container">
        {% for post in posts.items %}
        <div class="card bg-white rounded shadow-lg mt-5 mb-5">
            <div class="row">
                <div class="col-1">
            <img src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}" class="card-img-top mt-3 ml-3" style="max-width: 7vmin; border-radius: 50%;" alt="Profile Picture">
                </div>
            
            <div class="col">
            <div class="card-body">
                <h4 class="card-title d-flex">{{ post.title }}<span class="ml-auto text-muted">{{ post.created_at.strftime('%Y-%m-%d') }}</span></h4>
                <h6>by {{ post.author.username }}</h6>
                <hr />
                <h6 class="card-text">{{ post.content }}</h6>
                <div class="form-group d-flex">
                    <div class="ml-auto">
                    <a class="btn btn-outline-danger" href="{{ url_for('posts.delete_post',post_id=post.id) }}">delete</a>
                    <a class="btn btn-outline-info ml-2" href="{{ url_for('posts.update_post',post_id=post.id) }}">edit</a>
                </div>
                </div>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-dark mb-4" href="{{ url_for('main.home',page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-dark mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}     
               {% else %}
            ...
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

flaskApp/templates/login.html
{% extends "base.html" %}


{% block content %}
<div style="margin:auto;max-width:480px;height:560px;" class="shadow bg-white rounded p-5 mt-5">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="mb-3 text-center">Login</legend>
            <div class="form-group"> 
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control") }}
               
            </div>
            <div>
                <div class="form-group"> 
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control") }}
                   
                </div>
            </div>
        </fieldset>  
            <div class="form-group mt-3">
                {{ form.submit(class="btn btn-outline-dark") }}
            </div>
            <div class="text-muted ml-2">
            <small>Forgot Password ? <a href="{{ url_for('users.reset_password_request') }}">Go here</a></small>
        </div>
        <div class="ml-2">
            <small>Need an Account? <a href="{{ url_for('users.register') }}">Go here</a></small>
        </div>
          

    </form>

</div>
{% endblock %}

flaskApp/templates/post_form.html
{% extends "base.html" %}


{% block content %}
<div style="margin:auto;max-width:480px;height:560px;" class="shadow bg-white rounded p-5 mt-5">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group ">
            <legend class=" mb-3 text-center ">Create Post</legend>
            <div>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>   
                    {% else %}
                    {{ form.title(class="form-control") }}
                    {% endif %}
                    
                </div>
            </div>
            <div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>   
                {% else %}
                {{ form.content(class="form-control") }}
                {% endif %}
                
            </div>
            </div>
            <div class="form-group mt-3">
                {{ form.submit(class="btn btn-outline-dark") }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

flaskApp/templates/register.html
{% extends "base.html" %}


{% block content %}
<div style="margin:auto;max-width:480px" class="shadow bg-white rounded p-5 mt-5">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group ">
            <legend class=" mb-3 text-center ">Register</legend>
       
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>   
                {% else %}
                {{ form.username(class="form-control") }}
                {% endif %}
                
                
            </div>
            <div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>   
                    {% else %}
                    {{ form.email(class="form-control") }}
                    {% endif %}
                    
                </div>
            </div>
            <div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>   
                    {% else %}
                    {{ form.password(class="form-control") }}
                    {% endif %}
                    
                </div>
            </div>
            <div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>   
                {% else %}
                {{ form.confirm_password(class="form-control") }}
                {% endif %}
                
            </div>
            </div>
            <div class="form-group mt-3">
                {{ form.submit(class="btn btn-outline-dark") }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

flaskApp/templates/request_password.html
{% extends "base.html" %}


{% block content %}
<div style="margin:auto;max-width:480px;height:560px;" class="shadow bg-white rounded p-5 mt-5">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-5">Reset Password</legend>
            <div class="form-group">
               {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %} 
                {{ formemaile(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %} 
                </div>

                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
               
            </div>
            <div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

flaskApp/templates/reset_token.html
 {% extends "base.html" %}


{% block content %}
<div class="container bg-white rounded shadow-lg mt-5">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-5">{{ legend }}</legend>
            <div class="form-group">
               {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %} 
                </div>

                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
                
            </div>
            <div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control is-invalid") }}
                    <div class="invalid-feedback"></div>
                        {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                       {% else %}
                    {{ form.confirm_password(class="form-control") }}
                    {% endif %}
                    
                </div>
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}